### PR TITLE
Upgrade to Jandex 3.0.0

### PR DESCRIPTION
**Pull request by Ladicek**
Submitting as draft because this needs discussion on release coordination (I guess).

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Jandex is managed by the smallrye-parent pom currently. Will that be continued going forward?

**Comment by Ladicek** [comment]
Frankly, I just don't like how the SmallRye parent manages (or not) some versions. To me, it feels like a big dump of random stuff that is only updated when someone remembers and there's no coordination around it. In SmallRye Fault Tolerance, I don't even use it (I use `smallrye-build-parent`).

This is a relatively big/important change that requires coordination -- adding the parent POM to the mix would just make it worse. I propose we replace Jandex 2.x with Jandex 3.0 in the parent POM when things settle.

**Comment by Ladicek** [comment]
I also just noticed that SmallRye OpenAPI uses the `Type` hierarchy on a few places (`TypeProcessor`, `TypeResolver`). This code will likely have to be updated to deal with type variable references. In general, code that handles `UnresolvedTypeVariable` or `Type.Kind.UNRESOLVED_TYPE_VARIABLE` likely needs to be updated. I don't really understand how that code works, so I'll refrain from attempting to change it myself. Just letting you know.

**Review by MikeEdgar — APPROVED** [review]
lgtm - ignoring the code coverage check since they're just proxy methods and aren't being used (yet) anyway.

**Pull request merged**
