### PR TITLE
Run TCK with Arquillian, WELD and RESTEasy.

### PR DESCRIPTION
**Pull request by radcortez**
This is for us to have a more consistent environment to run the TCK for MP compliance.

The old TCK runner is still around. We can either remove it or keep it.

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Thanks @radcortez , this looks good. One question I have is regarding the Github action - should the path be testsuite/tck/target/... rather than tck/target/... ? Also, where are the files uploaded, as attachments to the repository?

**Comment by radcortez** [comment]
> Thanks @radcortez , this looks good. One question I have is regarding the Github action - should the path be testsuite/tck/target/... rather than tck/target/... ? 

Yes! Good catch.

> Also, where are the files uploaded, as attachments to the repository?

They are uploaded to each CI Build. Here is an example: https://github.com/smallrye/smallrye-config/actions/runs/398298378. The new MP Compatible Certification requires the TCK results to be accessible somehow. This was the easiest way to do it.

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
I think we should remove the 'old' TCK and remame this to TCK. @MikeEdgar  ? W.d.y.t ?

**Comment by phillip-kruger** [comment]
Merging this PR, if all agree we can remove old TCK in a separate PR.

**Comment by MikeEdgar** [comment]
@phillip-kruger - I agree, but there are a few non-TCK tests in that module that should be kept somewhere.

**Comment by phillip-kruger** [comment]
Good point ! Can we just add it to the new TCK module maybe ?

**Comment by MikeEdgar** [comment]
Maybe, but they rely on the custom framework the old TCK uses. It might be good to keep the new TCK module purely TCK tests. I can take a quick look and see if it's feasible to have them run differently.

**Comment by radcortez** [comment]
The additional tests still use the Arquillian annotations, so in theory,  they should work with the new TCK structure by removing the custo annotations and keeping the Arquillian stuff.

I can have a look into that if you prefer :)

**Pull request merged**
