### PR TITLE
Maven plugin: index output directory instead of project artifact, logs #1538 (2.3.x backport)

### PR DESCRIPTION
**Pull request by tuffnatty**

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@tuffnatty thank you for the PR. In issue 1436 you [mentioned](https://github.com/smallrye/smallrye-open-api/issues/1436#issuecomment-1752152661) JDK 1.8 compatibility. Recent versions should still be able to execute with Java 8, are you seeing different behavior? We don't run the CI with Java 8 anymore so it's possible some dependency has moved to Java 11 somewhere.

**Comment by tuffnatty** [comment]
@MikeEdgar The first problem that I encounter is formatter-maven-plugin, a dependency of smallrye-config. formatter-maven-plugin's last version supporting JDK 1.8 is 2.16. It was once downgraded from 2.17 to 2.16 in https://github.com/smallrye/smallrye-parent/issues/288,  then upgraded to 2.22 in https://github.com/smallrye/smallrye-parent/commit/d813e22e046307e8b646430a19dcd6af85358c36 which has been released in smallrye-parent 39. Do you suggest me raising an issue in smallrye-parent instead? Sadly I am totally unfamiliar with the smallrye infrastructure, I am only using your maven-plugin.

**Comment by MikeEdgar** [comment]
@tuffnatty , for sure JDK 11 is needed to build the plugin for the reasons you mentioned (and possibly others), but what about running it in your project? Do you have a need to build it separately from the released version?

**Comment by tuffnatty** [comment]
@MikeEdgar Thank you! Great news! I'm able to run the 3.6.2 version of the plugin if I override the following dependencies:
```xml
			<plugin>
				<artifactId>smallrye-open-api-maven-plugin</artifactId>
				<groupId>io.smallrye</groupId>
				<version>3.6.2</version>
				<dependencies>
					<dependency>
					    <groupId>io.smallrye.config</groupId>
					    <artifactId>smallrye-config</artifactId>
					    <version>2.13.3</version>
					</dependency>
					<dependency>
						<groupId>org.jboss.logging</groupId>
						<artifactId>jboss-logging</artifactId>
						<version>3.4.3.Final</version>
					</dependency>
                                </dependencies>
```
So my immediate problem is solved, but probably this piece of configuration can be better documented somewhere?

**Comment by MikeEdgar** [comment]
@tuffnatty , that would be great to add to the plugin's [README file](https://github.com/smallrye/smallrye-open-api/blob/40a312ce4be767f6a042eacf1ccddb986e411c3a/tools/maven-plugin/README.adoc?plain=1#L5) following the current simple example. Any interest in doing a PR for that addition?

**Comment by tuffnatty** [comment]
@MikeEdgar Thanks! Closing.

**Pull request closed without merging**
