### PR TITLE
Add logo for IntelliJ's project list

### PR DESCRIPTION
**Pull request by snazy**
Looks like this:
image

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@phillip-kruger wdyt?

**Comment by phillip-kruger** [comment]
Fine by me :) I am not using IntelliJ :) Your call.

**Review by MikeEdgar — COMMENTED** [review]
Since this falls into the category of IDE-specific configuration and we've historically ignored such files in `.gitignore`, I think it's better to skip this change. @snazy sound OK to you?

**Comment by snazy** [comment]
I don't mind :)

**Pull request closed without merging**
