### PR TITLE
Add multipleOf test

### PR DESCRIPTION
**Pull request by Azquelt**
`0.1` is used as the value here as it's not unusual and jandex currently has issues reading it.

This test won't pass until a new version of jandex is released and dependencies updated.

For #869

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Awesome ! thanks !

**Comment by phillip-kruger** [comment]
@MikeEdgar - After a rebase this PR still fails ?

**Comment by MikeEdgar** [comment]
@phillip-kruger We need to wait for Jandex 2.4 to merge this.

**Comment by phillip-kruger** [comment]
Aaa, ok cool. Do you have an idea on e.t.a for Jandex ?

**Comment by MikeEdgar** [comment]
I'm not sure, I have another PR there that should help with #716 that needs some additional testing.

**Pull request merged**
