### PR TITLE
Experimental support for multiple TCK versions

### LINKED ISSUE #1268: Investigate running multiple TCK versions
In order to reduce ongoing maintenance of multiple branches, it may be good to have a single version that passes multiple versions of the TCK - 2.0, 3.0, and 3.1 at the moment.

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #1268

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@radcortez , let me know if you think this is a viable approach to eliminating the need for maintaining multiple branches (pre-Jakarta, Jakarta, current MP 6). We'll continue to generate release 8 bytecode for as long as we need to support MP OpenAPI 2.0. This should be further refined to attach the one-page HTML TCK reports to releases.

/cc: @phillip-kruger

**Comment by radcortez** [comment]
Looks good. Are you able to pass the TCK with the same code between `javax` and `jakarta`?

**Comment by MikeEdgar** [comment]
> Looks good. Are you able to pass the TCK with the same code between `javax` and `jakarta`?

Yes, the scanner looks for both namespaces for all of the supported annotations. The only other thing I need to make sure of is that we're not using any methods new to Jandex 3 to ensure it works with the 2.4.x series if that's what is available.

**Comment by radcortez** [comment]
Great. I'm fine if you go with this approach.

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Pull request merged**
