### PR TITLE
Update NPM packages and use `npm ci` (requires package-lock.json)

### PR DESCRIPTION
**Pull request by MikeEdgar**
* Update several NPM packages / regenerate `package-lock.json`
* Remove use of `lock-treatment-tool` - seems unnecessary, but glad to keep it if there is a good case for using it
* Use `npm ci` to install dependencies based on fixed versions in `package-lock.json`

If this all looks OK I'll create a PR for `2.0.x` also.

CC: @tarilabs

### CODE REVIEW

**Comment by phillip-kruger** [comment]
@tarilabs - please review. Thanks @MikeEdgar !

**Review by tarilabs — APPROVED** [review]
Verified locally, thanks for the ping it looks good to me! 👍 

Another thing I wanted to take a look at this was to replace the form library with Uniforms so to try leverage a PatternFly theme, but I have very thin bandwidth and not able to make sure if it does cover all the functionalities.. happy to share more details if anyone is interested to spend some cycles!

screenshot of local built and verify:
image

**Comment by phillip-kruger** [comment]
Thanks @tarilabs !!

**Review by phillip-kruger — APPROVED** [review]
As per @tarilabs

**Pull request merged**
