### PR TITLE
Prepare next version (using MP 1.1-SNAPSHOT)

### PR DESCRIPTION
**Pull request by jmini**
See https://github.com/smallrye/smallrye-open-api/issues/44

### CODE REVIEW

**Comment by EricWittmann** [comment]
The build is failing with the following errors:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (default-cli) on project smallrye-open-api: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - /home/runner/smallrye-open-api/implementation/src/main/java/io/smallrye/openapi/api/models/ExtensibleImpl.java:54: error: unexpected text
[ERROR]      * @see null#removeExtension(java.lang.String)
[ERROR]        ^
[ERROR] /home/runner/smallrye-open-api/implementation/src/main/java/io/smallrye/openapi/api/models/responses/APIResponsesImpl.java:86: error: reference not found
[ERROR]      * @see org.eclipse.microprofile.openapi.models.responses.APIResponses#removeApiResponse(java.lang.String)
[ERROR]             ^
[ERROR] /home/runner/smallrye-open-api/implementation/src/main/java/io/smallrye/openapi/api/models/responses/APIResponsesImpl.java:89: warning - Tag @see: can't find removeApiResponse(java.lang.String) in org.eclipse.microprofile.openapi.models.responses.APIResponses
[ERROR] /home/runner/smallrye-open-api/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/FilteredIndexView.java:47: warning: no description for @param
[ERROR]      * @param delegate
[ERROR]        ^
[ERROR] /home/runner/smallrye-open-api/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/FilteredIndexView.java:48: warning: no description for @param
[ERROR]      * @param config
[ERROR]        ^
[ERROR] 
```

**Comment by jmini** [comment]
Now the error is:

```
[ERROR] Errors: 
[ERROR]   FilterTckTest.initializationError » NullPointer
```

I have it also locally, but I have no idea what changed there and why the test runner can not execute this test.

Can you have a look?

**Comment by EricWittmann** [comment]
Will do!

**Comment by EricWittmann** [comment]
OK I've actually made a number of changes and then merged this PR.  Thanks for this work!  Now we can collaborate on the `1.1` stuff via this branch.  (ping @msavy as an FYI)

Note that the `NullPointer` was due to a problem parsing and modelling the API responses.  The `default` response was being added to the data model even when it was null.  This was putting a `null` value in the map of responses, which was then causing an NPE later in the test.  Fixed by never storing nulls in the API responses map.  I'm not sure what changed on the TCK side to introduce this problem, but it was an obvious fix so I didn't dive deeper.

Also not that I've updated the `pom.xml` files to be more explicit about the dependencies, particularly where we were directly using certain classes but not actually directly depending on the libraries in which they live.  Hopefully I haven't messed anything up (e.g. forgotten a `scope` somewhere).  Happy to have some more eyes looking at this.

Finally, I want @msavy to know that I removed a bunch of `@SuppressWarnings` annotations for unused fields and whatnot from some test classes.  I know we have often have different Eclipse settings for this which has caused one or the other of us to see IDE warnings.  In the future if an IDE complains about unused classes or variables, I suggest we create additional test classes that actually use those variables (but themselves are otherwise not referenced anywhere) rather than suppress the warning.

**Pull request merged**
