### PR TITLE
Schema annotations 3.1

### PR DESCRIPTION
**Pull request by Azquelt**
Implement the `@Schema` and `@SchemaProperty` changes from eclipse/microprofile-open-api#601.

I haven't duplicated cases which are already covered by the TCK.

### CODE REVIEW

**Comment by Azquelt** [comment]
In e83724a I made some of the scanner tests output the actual JSON document in the event of a failure because it was more helpful to me during development than configuring logging and finding the logs, but that part is not relevant to the actual changes and can be dropped if desired.

**Comment by Azquelt** [comment]
CI will not run cleanly until eclipse/microprofile-open-api#601 is merged but I have built and run this change locally with no failures.

**Review by MikeEdgar — APPROVED** [review]
Looks good. Let's leave it open until there's a good run of the TCK against a new MP snapshot.

**Comment by Azquelt** [comment]
@MikeEdgar we now have a good build

**Pull request merged**
