### PR TITLE
Customize the MicroProfile OpenAPI TCK Report

### PR DESCRIPTION
**Pull request by MikeEdgar**
TCK report customization to list SmallRye and MP versions

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Sample reports attached
[tck-report-2.0.1.zip](https://github.com/smallrye/smallrye-open-api/files/9802716/tck-report-2.0.1.zip)
[tck-report-3.0.zip](https://github.com/smallrye/smallrye-open-api/files/9802717/tck-report-3.0.zip)
[tck-report-3.1.zip](https://github.com/smallrye/smallrye-open-api/files/9802718/tck-report-3.1.zip)

**Comment by MikeEdgar** [comment]
@radcortez , @phillip-kruger - please take a look at the attached reports and let me know if you have any concerns on formatting or otherwise. I intend to manually attach these to the GitHub release for 3.1 to address David's comment on the 2.0 certification request [1]. Eventually, these can be automatically attached.

[1] https://github.com/eclipse/microprofile-open-api/issues/459#issuecomment-748362004

**Comment by radcortez** [comment]
Check this: https://github.com/smallrye/smallrye-config/blob/main/.github/workflows/release.yml#L72-L85

This generates the tck-report from surefire and uploads it automatically to the GH Release: https://github.com/smallrye/smallrye-config/releases/tag/2.12.1

**Comment by radcortez** [comment]
Anyway, the reports looks great!

**Review by radcortez — APPROVED** [review]

**Comment by MikeEdgar** [comment]
Updated the report to include some additional information about the build and versions and also added the TCK execution and upload to the release job.
image

**Pull request merged**
