### PR TITLE
Use Maven managed versions for junit and jackson in Gradle plugin

### LINKED ISSUE #1321: Schemas for classes in dependency JARs never generated
Hello,

Not sure if this is a bug or a configuration issue, but I am trying to use the gradle plugin with a vanilla microprofile project (simple WAR generated and loaded into a TomEE instance). I have run into the following issue:

Let's assume a library A is included as compileOnly and some object MyObject from A is used either as a request body or response. Basically:

```
public Response appendNetwork(@RequestBody MyObject myObject) throws Exception {
        //do stuff with my object here.
        return Response.ok().build();
    }
```     

When I run the gradle task below everything gets generated correctly except the schema for MyObject which results in the following errors in the debug ``` [io.smallrye.openapi.runtime.scanner] SROAP04005: Could not find schema class in index: MyObject``` (assume that MyObject is included correctly as some ```com.mypackage.whatever.MyObject```)

```
generateOpenApiSpec {
    outputDirectory = new File(this.getProjectDir().toString() + "/src/main/resources/openapi")
    scanDependenciesDisable = false
}
```
Is this a limitation or am I missing some configuration here?

As a possible hint when using the 'io.swagger.core.v3.swagger-gradle-plugin' version '2.1.11' the same problem surfaces but it can be mitigated with the following configuration of the plugin, in which case MyObject is indeed found and correctly included as a schema in the OpenAPI specification:

```
resolve {
    outputFileName = 'api'
    outputFormat = 'YAML'
    prettyPrint = 'TRUE'
    classpath = sourceSets.main.output + configurations.compileClasspath
    buildClasspath = classpath
}
```

### LINKED ISSUE #1339: Gradle plugin crashes with Jackson-related stacktrace
I am trying the gradle plugin but it doesn't work out of the box

## Setup

* Building plugin from `main` / 3.1.2-SNAPSHOT
* Gradle 7.5.1
* Added plugin to gradle project using
```
plugins {
  id("io.smallrye.openapi") version "3.1.2-SNAPSHOT"
}

generateOpenApiSpec {
  scanPackages = ["com.myproject"]
}
```
* Build using `gradle clean build --stacktrace`

## Behavior

In stead of succeeding, the build fails with the following stack trace (snippet):

```
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createGenerator(YAMLFactory.java:441)
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createGenerator(YAMLFactory.java:15)
        at com.fasterxml.jackson.databind.ObjectWriter.createGenerator(ObjectWriter.java:703)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1086)
        at io.smallrye.openapi.runtime.io.OpenApiSerializer.serialize(OpenApiSerializer.java:48)
        at io.smallrye.openapi.gradleplugin.SmallryeOpenApiTask.write(SmallryeOpenApiTask.java:298)
        at io.smallrye.openapi.gradleplugin.SmallryeOpenApiTask.generate(SmallryeOpenApiTask.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

This can be traced down to a different version of `jackson-core` being used (that has the `JSONFactory` class) vs `jackson-dataformat-yaml` (that has `YAMLFactory, calling the _createContentReference() method). 

Plugin classpath:

```
> Task :public:api:buildEnvironment

------------------------------------------------------------
Project ':public:api'
------------------------------------------------------------

classpath
\--- io.smallrye.openapi:io.smallrye.openapi.gradle.plugin:3.1.2-SNAPSHOT
     \--- io.smallrye:smallrye-open-api-gradle-plugin:3.1.2-SNAPSHOT
          +--- io.smallrye:smallrye-open-api-core:3.1.2-SNAPSHOT
          |    +--- org.eclipse.microprofile.openapi:microprofile-openapi-api:3.1
          |    +--- org.eclipse.microprofile.config:microprofile-config-api:3.0
          |    +--- com.fasterxml.jackson.core:jackson-core:2.13.4
          |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4
          |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4 (c)
          |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (c)
          |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (c)
          |    |         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.4 (c)
          |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2
          |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4
          |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
          |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (*)
          |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
          |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.4
          |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (*)
          |    |    +--- org.yaml:snakeyaml:1.31
          |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (*)
          |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
          |    +--- io.smallrye:jandex:3.0.5
          |    \--- org.jboss.logging:jboss-logging:3.5.0.Final
          +--- io.smallrye:smallrye-open-api-jaxrs:3.1.2-SNAPSHOT
          |    +--- io.smallrye:smallrye-open-api-core:3.1.2-SNAPSHOT (*)
          |    \--- org.jboss.logging:jboss-logging:3.5.0.Final
          +--- io.smallrye:smallrye-open-api-spring:3.1.2-SNAPSHOT
          |    +--- io.smallrye:smallrye-open-api-core:3.1.2-SNAPSHOT (*)
          |    \--- org.jboss.logging:jboss-logging:3.5.0.Final
          \--- io.smallrye:smallrye-open-api-vertx:3.1.2-SNAPSHOT
               +--- io.smallrye:smallrye-open-api-core:3.1.2-SNAPSHOT (*)
               \--- org.jboss.logging:jboss-logging:3.5.0.Final

(c) - dependency constraint
(*) - dependencies omitted (listed previously)
```

## Workaround

Works when I revert to Jackson 2.12.0 in the main `pom.xml` of the SmallRye project and rebuild the plugin.

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #1339
Fixes #1321 

Signed-off-by: Michael Edgar <michael@xlate.io>

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@Hes-Siemelink - if you get a chance, please let me know if this change resolves the issue in your test project from #1339. Thank you!

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by Hes-Siemelink** [comment]
Hi Mike, thanks for looking into this! At first glance it doesn't solve the crash I have. It could be that it is not the small rye plugin that is at fault, but it is an issue with the gradle project on my end. The behavior is strange, because gradle reports a correct class path with `gradle buildEnvironment` but the build still fails with the same stack trace. Let me double check and get back to you.

**Comment by sidohin-felix** [comment]
@MikeEdgar I tried testing the plugin from the master build, unfortunately it still seems that libraries defined as compile only JARs returns **SROAP04005: Could not find schema class in index:** for classes which are defined inside an external library. Maybe I'm not configuring something properly or should I set the compileclass path somehow as I was mentioning in #1321

**Comment by Hes-Siemelink** [comment]
Same here with dependencies define in `build.gradle` as

```
dependencies {
  api project(":core:domain")
```

Resulting in classes from `domain` not being found:

```
SROAP04005: Could not find schema class in index: core.domain.Configuration
...
```

Gradle version is 7.5.1

**Pull request merged**
