### PR TITLE
Update MP OpenAPI to 2.0.1

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Review by MikeEdgar — APPROVED** [review]
LGTM. Were you looking to get this into a release? I just did one earlier today...

**Comment by radcortez** [comment]
> LGTM. Were you looking to get this into a release? I just did one earlier today...

Yes :(

It is required for Quarkus product. Can we do another?

**Comment by MikeEdgar** [comment]
Yes, fine with me.

**Comment by radcortez** [comment]
Ok, I'll do it.

**Pull request merged**
