### PR TITLE
Keep the order for server configuration

### PR DESCRIPTION
**Pull request by gsmet**
Related to https://github.com/quarkusio/quarkus/issues/29444

### CODE REVIEW

**Comment by gsmet** [comment]
I'm not very accustomed to this project but this change looks like a good thing to me. Let me know what you think.

(And hopefully, the TCKs will pass...)

**Review by MikeEdgar — APPROVED** [review]
LGTM, thanks @gsmet. Mind if we keep this for 3.1.1? We just had 3.1.0 certified for the spec release and I'd like to keep the core modules unchanged if possible. We can do 3.1.1 immediately after.

**Comment by gsmet** [comment]
Sure. Any chance you could also backport it to 2.x so that we get it in Quarkus before Quarkus 3?

I can prepare a specific PR if it doesn't apply cleanly (I don't know what's your backport process here).

**Comment by MikeEdgar** [comment]
Yes, I'll backport it to 2.x. It's usually just a PR with a collection of cherry-picked commits from `main`.

**Comment by gsmet** [comment]
Perfect, then. Thanks!

**Pull request merged**
