### PR TITLE
Updated the version to 1.3.0 to match the MP version

### PR DESCRIPTION
**Pull request by EricWittmann**
Signed-off-by: Eric Wittmann <eric.wittmann@gmail.com>

### CODE REVIEW

**Comment by kenfinnigan** [comment]
@EricWittmann, I think I gave you slightly obtuse information the other day!

The version this needs to be is the MP Open API spec version, so I think that would be 1.0.0 for current implementation?

**Comment by EricWittmann** [comment]
OK that actually makes more sense.  The MP+OAI spec is currently at 1.0.1.

**Comment by EricWittmann** [comment]
Well I guess the spec itself is version 1.0.  Is that right, @arthurdm ?

**Comment by EricWittmann** [comment]
My problem with pinning the smallrye version to the spec version that tightly (at the patch level) is that it leaves little room for the impl to evolve.  So imagine if we release smallrye-open-api 1.0.1 and then we find a bug (hard as that might be to believe), what version do we release?  I suppose we can go with a 4th digit:  1.0.1.1 in that case.

Thoughts @kenfinnigan @arthurdm @msavy @AndyGee ?

**Comment by kenfinnigan** [comment]
My initial ideas around version alignment were only at the major and minor level.

Whether a spec is at 1.0.0 or 1.0.1 doesn't impact the version that this impl will be released under.

For instance, 1.0.0 of a spec could be released and 1.0.0 of SmallRye shortly after. Then there could be a few patch releases that fix implementation issues, so we're now at 1.0.3. If 1.0.1 of the spec is then released, it would push the release of the implementation to 1.0.4.

It's only necessary to align impl and spec at the major/minor level, patch is inconsequential from a spec perspective, and required from an impl perspective to provide room for iterations and fixes

**Comment by EricWittmann** [comment]
That sounds reasonable to me. Thanks @kenfinnigan

**Pull request closed without merging**
