### PR TITLE
Avoid NPE when generic type variable declared outside type hierarchy

### PR DESCRIPTION
**Pull request by pferraro**
Port #237 from master.

### CODE REVIEW

**Comment by radcortez** [comment]
I'll add the GH Actions to 1.1.x for release.

**Comment by radcortez** [comment]
Let me know if this is good to be released.

**Comment by pferraro** [comment]
@MikeEdgar WF master (what will be WF20) is using 1.2.3. This backport is targeting 19.1.x.

**Comment by radcortez** [comment]
@pferraro after merge are we good for a release? or do you need something else?

**Comment by pferraro** [comment]
@radcortez I think we are good to release.  Thanks!

**Comment by radcortez** [comment]
Great. I'll push a release then.

**Pull request merged**
