### PR TITLE
Expose annotated XML attributes/elements when XmlAccessorType is NONE

### LINKED ISSUE #1504: XML attributes/elements ignored when class is annotated with XmlAccessType.NONE
See https://github.com/quarkusio/quarkus/issues/34402

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #1504

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by troosan** [comment]
@MikeEdgar There is an issue when the name in the XmlResponse does not match the method name
image

it then returns
image

**Comment by troosan** [comment]
Also the XmlType does not seem to be taken into account, for the name of the type and the order of the elements
image

**Comment by troosan** [comment]
the good new though is that the change seems to be compatible with 2.x (except for the Annotations class that was added later and which I had to change back to TypeUtil

**Comment by MikeEdgar** [comment]
Thanks for reporting this @troosan . It seems the XML support can be improved a bit. Would you mind putting your findings about the missing name support into a new issue?

**Comment by troosan** [comment]
> Thanks for reporting this @troosan . It seems the XML support can be improved a bit. Would you mind putting your findings about the missing name support into a new issue?

done, see #1510

**Pull request merged**
