### PR TITLE
Scan Kotlin nullability annotations

### LINKED ISSUE #716: Support kotlin nullable/non-nullable types as if explicitly set @Schema(required=true/false)
Referring to https://github.com/smallrye/smallrye-open-api/issues/714#issuecomment-789527358 :

Kotlin language has support for [nullable types](https://kotlinlang.org/docs/null-safety.html#nullable-types-and-non-null-types) where you explicitly need to state whether they can be null or not. This should translate to `@Schema(required=true/false)`.

To support this, it would be sufficient to check for the existence of `org.jetbrains.annotations.{Nullable, NotNull}` annotations. As far as I understand, https://github.com/smallrye/smallrye-open-api/issues/131 adds support for `javax.validation.constraints.NotNull` already, so this might be a minor addition?

Of course, I'd rather ike to have the kotlin compiler to support generating the `javax.validation.constraints.NotNull` annotations, but this currently seems not easily possible for reasons beyond my knowledge.

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #716

### CODE REVIEW

**Comment by asafalima** [comment]
Hi @MikeEdgar can we please create a new release? we really need this fix :)

**Comment by MikeEdgar** [comment]
> can we please create a new release? we really need this fix :)

I'll look to get one put together in the next few days.

**Comment by asafalima** [comment]
> > can we please create a new release? we really need this fix :)
> 
> I'll look to get one put together in the next few days.

Thank you for your quick response @MikeEdgar.
@DmitriyO FYI

**Comment by asafalima** [comment]
> > can we please create a new release? we really need this fix :)
> 
> I'll look to get one put together in the next few days.

Hi @MikeEdgar , any new regarding the new release?

**Comment by MikeEdgar** [comment]
@asafalima - release 2.3.1 is out! It should also be updated in Quarkus shortly if all goes well - https://github.com/quarkusio/quarkus/pull/28611

**Pull request merged**
