### PR TITLE
Read nested `extensions` property from extensible model annotations

### PR DESCRIPTION
**Pull request by MikeEdgar**
Implementation for https://github.com/eclipse/microprofile-open-api/pull/513

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@phillip-kruger please have a look when you get a chance. Once this is merged, I'd like to rebase and merge each of the MP 3.1 milestone PRs in order.

**Comment by phillip-kruger** [comment]
hi @MikeEdgar - can you look at the build failures ?

**Comment by MikeEdgar** [comment]
@phillip-kruger, several of these PRs will fail because the build is using the MP 3.1 snapshot with new tests. Each one that is rebased should have fewer test failures and the final PR should be green :-) If there is anything still broken after that, I'll open a separate PR to fix.

**Comment by phillip-kruger** [comment]
Ok cool. I just wanted to make sure :) Code changes l.g.t.m

**Review by phillip-kruger — APPROVED** [review]

**Pull request merged**
