### PR TITLE
Add test for Kotlin continuation in requestBody

### PR DESCRIPTION
**Pull request by rgmz**
Two things to note:

1. The schema generated by the [reproducer application](https://github.com/rgmz/quarkus-kotlin-openapi-21509) (which I used to model the `Resource` class) differs from that generated in tests. It's possible that: **a)** it's a Quarkus-specific issue; **b)** the test aren't accurately representing "real" Kotlin class files; **c)** there's an additional step not currently performed in the tests which cases this.

   ```yml
	---
	openapi: 3.0.3
	info:
	  title: quarkus-kotlin-openapi API
	  version: 1.0.0-SNAPSHOT
	paths:
	  /hello:
	    get:
	      tags:
	      - Reactive Greeting Resource
	      requestBody:
		content:
		  application/json:
		    schema:
		      $ref: '#/components/schemas/ContinuationSuperString'
	      responses:
		"200":
		  description: OK
		  content:
		    text/plain:
		      schema:
			type: string
	components:
	  schemas:
	    ContinuationSuperString:
	      type: object
	      properties:
		context:
		  $ref: '#/components/schemas/CoroutineContext'
	    CoroutineContext:
	      type: object
    ```

2. Using the Kotlin Decompiler in IntelliJ produces code with raw `Continuation` types. The schema works as expected when I manually change those to `Continuation<? super String>`, however, this leads me to believe that the cause may be **(b)**.

   `Continuation<? super String>` works as expected:
   ```yml
    openapi: 3.0.3
    paths:
      "/hello":
        get:
          responses:
            '200':
              description: OK
              content:
                text/plain:
                  schema:
                    type: string
   ```
   
   With `Continuation`
   ```yml
    openapi: 3.0.3
    paths:
      "/hello":
        get:
          responses:
            '200':
              description: OK
              content:
                text/plain:
                  schema:
                    type: object
   ```

### CODE REVIEW

**Comment by MikeEdgar** [comment]
If I remember correctly, the Kotlin to Java function in Intellij drops the generic type information from the bytecode. I think if you look at the Kotlin class in the bytecode viewer it's apparent that the generic information is still there in the method attributes.

**Comment by rgmz** [comment]
> I think if you look at the Kotlin class in the bytecode viewer it's apparent that the generic information is still there in the method attributes.

Ah, you're right:
```
  // access flags 0x1
  // signature (Lkotlin/coroutines/Continuation<-Ljava/lang/String;>;)Ljava/lang/Object;
  // declaration:  hello(kotlin.coroutines.Continuation<? super java.lang.String>)
  public hello(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
```

Given that the tests are working as expected, I'm thinking that it's a Quarkus issue after all (see my comment in #969).

**Comment by MikeEdgar** [comment]
@rgmz - just to test get more information, maybe see if you can create a jar of the problematic project, add it as a test dependency to the unit test and attempt to scan those classes directly.

**Comment by rgmz** [comment]
@MikeEdgar: Excellent idea.

That generates the expected response, which furthers my suspicion that the jaxrs extension isn't being applied in `quarkus-smallrye-openapi`.

Test:
```java
@Test
void testKotlinContinuationRequestBody() throws IOException, JSONException {
     Index index = Index.of(ReactiveGreetingResource.class, String.class);
    OpenApiAnnotationScanner scanner = new OpenApiAnnotationScanner(emptyConfig(), index);
    OpenAPI result = scanner.scan();
    printToConsole(result);
    assertJsonEquals("responses.kotlin-continuation-no-body.json", result);
}
```

Schema:
```json
{
  "openapi" : "3.0.3",
  "paths" : {
    "/hello" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by phillip-kruger** [comment]
@MikeEdgar - This build still fails ? Can you have a look ?

**Comment by MikeEdgar** [comment]
Let's close this for now. @rgmz , please let us know if the issue is not resolved when 2.1.16 is released.

**Pull request closed without merging**
