### PR TITLE
Fix UI `syntaxHighlight` option not support Object value

### LINKED ISSUE #1502: Swagger UI cannot render Object type `syntaxHighlight` property
Hi,

I'm using Quarkus & `quarkus-smallrye-openapi` package for rendering Swagger UI for API documentation of my project.

## Problem

I play around some configurations to make the page look nice, but found out that `syntaxHighlight` option is not working as expected. Viewing the source code of `/q/swagger-ui` page shows that `SwaggerUIBundle()` does get a `syntaxHighlight` option, but the value is rendered as String `'{ activate: true, theme: "monokai" }'`.

In [Swagger UI configuration](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) page,
`syntaxHighlight` can be boolean value `false` to disable it, or an object value `{ activate: true, theme: "monokai" }` to change the theme of syntax highlighting.

## Some Code Digging

In [Quarkus implementation](https://github.com/quarkusio/quarkus/blob/33940eefcde4cb673750901febb6a3cb8641fb8b/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java#L431), it will collect all configurations into a `Map<io.smallrye.openapi.ui.Option, String>` options, then it call `io.smallrye.openapi.ui.IndexHtmlCreator.createIndexHtml(...)` to get Swagger UI HTML content.

`IndexHtmlCreator` does [handle some special option values when replacing HTML template variables](https://github.com/smallrye/smallrye-open-api/blob/525f0e30b87f1daa07ffbee1b32316fc7edfd6fc/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexHtmlCreator.java#L63-L109), such as string starts with `function` or boolean values.

But `syntaxHighlight` property is either `Boolean` or `Object` values, I think `replace()` function can add another condition to handle this option.

## Possible Solution

Add an additional condition for `syntaxHighlight` in `ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexHtmlCreator.java` `render()` function:

```java
if (BOOLEAN_OR_OBJECT_KEYS.contains(variableOption)) {
    if (!replacement.equals("true") && !replacement.equals("false") &&
        !(replacement.startsWith("{") && replacement.endsWith("}"))) {
        replacement = "'" + replacement + "'";
    }
}
```

and move `syntaxHighlight` options from `BOOLEAN_OR_STRING_KEYS` into new category `BOOLEAN_OR_OBJECT_KEYS`

```java
// Some properties can be a boolean or a String. To render correct we need to handle those specially
private static final List<Option> BOOLEAN_OR_STRING_KEYS = Arrays
        .asList(new Option[] { Option.filter });

// Some properties can be a boolean or an Object. To render correct we need to handle those specially
private static final List<Option> BOOLEAN_OR_OBJECT_KEYS = Arrays
        .asList(new Option[] { Option.syntaxHighlight });
```

This is my first time reporting issue on a open-source project. Hope I didn't miss anything.

Thanks!

### PR DESCRIPTION
**Pull request by awashharp**
Fix #1502 using proposed solution.

I add 2 test cases to check the solution is working as expected.

### CODE REVIEW

**Comment by awashharp** [comment]
Seems like some code formatting problem. But it's getting late in my timezone, I'll fix it tomorrow.

**Review by phillip-kruger — APPROVED** [review]
LGTM. Can you rebase on main, build locally (for formatting) then force push.

**Comment by phillip-kruger** [comment]
thanks @awashharp !

**Comment by phillip-kruger** [comment]
> LGTM. Can you rebase on main, build locally (for formatting) then force push.

Not too worry, I done that :)

**Review by phillip-kruger — APPROVED** [review]

**Pull request merged**
