### PR TITLE
Resolve Sonar bugs, vulnerabilities, and security hot spots

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes several higher-priority Sonar issues.

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Somehow the Sonar analysis failed for the merge according to sonarcloud. :-\

**Comment by phillip-kruger** [comment]
mmm, some of the rules in Sonar is just silly....

**Comment by MikeEdgar** [comment]
Yeah, there are a lot of them. I like to reduce the noise so that the important issues stand out if they arise. I'm planning on taking a look at de-duplicating the `ParameterProcessor` classes next. That should get things back to "green".

**Comment by phillip-kruger** [comment]
yea there should be a lot that can be done there. I tried but reverted as I pained myself in a corner ...

**Pull request merged**
