### PR TITLE
Add i18n logging and messaging [#318]

### PR DESCRIPTION
**Pull request by mcserra**

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Would it make sense for the interfaces and the `BasicLogger` contained therein to be named the same in each package? It might be nice to look in a package and always expect to see a `Messages` interface without much thought. Similarly all of the logging calls would look like `Messages.log.particularLogStatement(...)` where "Messages.log" is the same everywhere.

**Comment by mcserra** [comment]
Makes sense. If being different from the other implementations is not a problem, I'll do it. Just let me know.

**Comment by MikeEdgar** [comment]
It's really just a preference. We can wait and see if anyone else has thoughts on it. Also, to your point, it would be different from the other implementations.

**Comment by MikeEdgar** [comment]
@EricWittmann, @phillip-kruger - one last question on this one. Is there anything that needs to be considered here regarding non-RH consumers of this library that have been discussed recently?

**Comment by phillip-kruger** [comment]
Hi @MikeEdgar - nothing that I know of. Let's merge this, we can always do more PRs to add/change things.

**Pull request merged**
