### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by phillip-kruger**
Hi guys.
As you know I am doing a refactor of the code.
I am creating this draft PR so that you can have a look and comment so long.

Mostly I have just broke classes up into smaller pieces and moved things around.

Here a high level list of things so long:

- SPI Factory to load scanners (JAX-RS being the only one for now)
- Broke OpenApiAnnotationScanner up into smaller reader classes.
- Broke OpenApiParser up into smaller writer classes
- Broke OpenApiConstants up into smaller classes
- Create smaller methods when doing JAX-RS scanning

All test is still passing.

Next I want to 
- Add a Spring scanner.
- Refactor JAX-RS Scanner some more

Please have a look and comment. In general classes and methods are smaller, and that does make is easier to move things around. I still have a lot to do, but would appreciate any feedback so far.

### CODE REVIEW

**Comment by MikeEdgar** [comment]
This looks like a nice improvement. A couple questions:

* Why were the copyright / license headers removed?
* Will Spring scanning be in this PR or will that come separately?

**Comment by phillip-kruger** [comment]
Hi @MikeEdgar 
Thanks for having a look.
1) We do not need license in the source code for smallrye. (there is a LICENSE file). this comes from Ken.
2) It depends. I was planning on doing as part of this, but I do not want to hold up other fixes. What do you think ?

**Comment by MikeEdgar** [comment]
Does there need to be a distinction between the copyright section and the license section of the headers? I personally think it makes sense to split it into two PRs. That will help make the Spring changes easier to digest.

**Comment by phillip-kruger** [comment]
I'll double check the copyright/licence with Ken.
Right, I'll make it two separate PRs. I am currently busy working on the JAX-RS part. Once that is done, maybe we can review and merge, then I do the Spring part.

**Comment by EricWittmann** [comment]
This may be a separate potential improvement, but I wonder if we should look at leveraging https://github.com/Apicurio/apicurio-data-models for the I/O (parsing, writing) of the OpenAPI.  I'm not sure it's feasible given how Microprofile OpenAPI has its own model interfaces (which may not be compatible).  But perhaps we can discuss if it's useful and whether it could be accomplished.  We have a lot of testing in that library and it provides quite a lot of functionality that could be leveraged for SmallRye OpenAPI features (e.g. validation).

**Comment by phillip-kruger** [comment]
Hi @EricWittmann . That sounds promising. Can we create a ticket to look at that at some point ?

**Comment by phillip-kruger** [comment]
On a separate note, the last part of my refactor is to move JAX-RS out into it's own module so I am thinking to do this, we have the following modules:

core - that is the bulk of the OpenAPI code. (readers/writers etc)
extension-jaxrs - that depend on core and add the JAX-RS entrypoint.
implementation (like we have it today) that include the above two modules.
extension-spring - that can optionally be added with the implementation to add Spring support.

WDYT ?

**Comment by phillip-kruger** [comment]
Right, I have changed the module structure as follows:

- **core** where most of the OpenAPI code is, the readers/writers and loading from file, etc. This module has **no** dependency on JAX-RS (or Spring)
- **extension-jaxrs** I pulled the JAX-RS Specific classes into this module. This module depends on JAX-RS and core. There are still parts in there that I believe can be "pulled-up" into core, but that would become clear as we implement the Spring part.
- **extension-spring** Just the structure, still empty. To be done. This will depend on Spring and core
- **implementation** - This is now a "pom" module. At the moment it depend on core and extension-jaxrs to give us the same as we have. We can later add extension-spring if we want to make that part of the implementation by default, or not if we want runtimes to pull that in manually
- **tck** - No change here.

I think we are at a good point for a review and merge. Then we can start with the Spring part and possibly some more re-factoring.

**Comment by phillip-kruger** [comment]
@MikeEdgar @EricWittmann please review and let me know. 
Thanks :)

**Comment by phillip-kruger** [comment]
OK, hold on, there are TCK failures. Let me look at those first.

**Comment by phillip-kruger** [comment]
@MikeEdgar @EricWittmann semaphoreci now building. Please review !

**Comment by MikeEdgar** [comment]
@phillip-kruger - I haven't had a chance to get through this all the way yet, but I noticed something has happened with the Sonar code coverage. Did you see that?

**Comment by phillip-kruger** [comment]
@MikeEdgar - no worries. No I have not looked at sonar yet. Will do so now

**Comment by phillip-kruger** [comment]
Hi @MikeEdgar - are you talking about https://sonarcloud.io/dashboard?id=smallrye_smallrye-open-api ?

**Comment by MikeEdgar** [comment]
@phillip-kruger - yes that's right. I think it's actually been like that since March 5th or so.

**Comment by phillip-kruger** [comment]
Yes, that is looking at master (so before this PR). March 5 is my previous PR:
https://github.com/smallrye/smallrye-open-api/pull/271/files

Not sure why  ?

**Comment by MikeEdgar** [comment]
It says master, but it's actually the latest build, both PRs and merges into master. The previous way of doing it was to have each module collect JaCoCo statistics and finally the TCK module aggregated them for the Sonar plugin. There is a `sonar.coverage.jacoco.xmlReportPaths` property in the parent POM with the aggregate report path used by that plugin during the build. 

I found it easier to test by creating the project in my own Sonar account with a personal key and running the plugin locally. If you end up taking a look and it's not an easy fix, I can take a look at it using this PR branch.

**Comment by phillip-kruger** [comment]
Ok cool. Yes please let me know once you had a look

**Comment by phillip-kruger** [comment]
OK let me look in my own sonar account.

**Comment by EricWittmann** [comment]
@phillip-kruger Since this diff is fairly brutal (renames, header removals, etc) would you be willing to do a live tour of the changes?  e.g. using Bluejeans or Google Meet

**Comment by phillip-kruger** [comment]
@EricWittmann for sure ! Let's discuss on mail

**Comment by phillip-kruger** [comment]
@MikeEdgar - the coverage is back to where it was. Weirdly, if you mark the dependencies as scope test in the TCK (which they are) that breaks the coverage. I also resolved to other 'code smells' from sonar, so overall the report looks better.

**Pull request merged**
